//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComboBox {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComboBox.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHINA.
        /// </summary>
        public static string chi {
            get {
                return ResourceManager.GetString("chi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME LIST :.
        /// </summary>
        public static string con {
            get {
                return ResourceManager.GetString("con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INDIA.
        /// </summary>
        public static string ind {
            get {
                return ResourceManager.GetString("ind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KARNATAKA.
        /// </summary>
        public static string kar {
            get {
                return ResourceManager.GetString("kar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KERALA.
        /// </summary>
        public static string kl {
            get {
                return ResourceManager.GetString("kl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  NAME :.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNTRY :.
        /// </summary>
        public static string nation {
            get {
                return ResourceManager.GetString("nation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAKISTHAN.
        /// </summary>
        public static string pak {
            get {
                return ResourceManager.GetString("pak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATE :.
        /// </summary>
        public static string sta {
            get {
                return ResourceManager.GetString("sta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAMILNADU.
        /// </summary>
        public static string tamil {
            get {
                return ResourceManager.GetString("tamil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TELUGANA.
        /// </summary>
        public static string tel {
            get {
                return ResourceManager.GetString("tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA.
        /// </summary>
        public static string us {
            get {
                return ResourceManager.GetString("us", resourceCulture);
            }
        }
    }
}
